import {
  collection,
  deleteDoc,
  doc,
  onSnapshot,
  orderBy,
  query,
  setDoc,
  where,
} from "firebase/firestore";
import {
  deleteObject,
  getDownloadURL,
  ref as storageRef,
} from "firebase/storage";
import { firestore, storage } from "./firebaseClient";
import type { GeneratedImage, ProductItem } from "../types";
import { RETENTION_DAYS_BY_TIER, computeExpiresAt } from "../shared/tiers";

export { RETENTION_DAYS_BY_TIER, computeExpiresAt };

export function subscribeToGallery(
  uid: string,
  onChange: (images: GeneratedImage[]) => void,
): () => void {
  const galleryRef = collection(firestore, "users", uid, "gallery");
  const q = query(
    galleryRef,
    where("expiresAt", ">", Date.now()),
    orderBy("expiresAt", "desc"),
  );

  return onSnapshot(q, async (snap) => {
    const images: GeneratedImage[] = [];
    snap.forEach((d) => images.push(d.data() as GeneratedImage));
    const now = Date.now();
    const live = images.filter((img) => img.expiresAt > now);

    // Resolve thumbnail download URLs for any images whose thumbnail was
    // generated by the onGalleryImageFinalize Function. Originals fall back to
    // the full-size `url`.
    const withThumbs = await Promise.all(
      live.map(async (img) => {
        if (!img.thumbnailPath || img.thumbnailUrl) return img;
        try {
          const url = await getDownloadURL(storageRef(storage, img.thumbnailPath));
          return { ...img, thumbnailUrl: url };
        } catch {
          return img;
        }
      }),
    );

    withThumbs.sort((a, b) => b.createdAt - a.createdAt);
    onChange(withThumbs);
  });
}

export async function saveProductsToImage(
  uid: string,
  imageId: string,
  products: ProductItem[],
): Promise<void> {
  const docRef = doc(firestore, "users", uid, "gallery", imageId);
  await setDoc(docRef, { savedProducts: products }, { merge: true });
}

export async function deleteGalleryImage(
  uid: string,
  imageId: string,
  storagePath?: string,
): Promise<void> {
  await deleteDoc(doc(firestore, "users", uid, "gallery", imageId));
  if (storagePath) {
    try {
      await deleteObject(storageRef(storage, storagePath));
    } catch {
      // Object may already be gone (lifecycle delete) — non-fatal
    }
  }
}
