import React from "react";
import { X } from "lucide-react";

export type LegalDocKind = "terms" | "privacy";

interface TermsModalProps {
  kind: LegalDocKind;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ kind, onClose }) => {
  const isTerms = kind === "terms";
  const title = isTerms ? "Terms & Conditions" : "Privacy Policy";
  const body = isTerms ? TERMS_BODY : PRIVACY_BODY;

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade"
      onClick={onClose}
    >
      <div
        className="bg-google-surface w-full max-w-2xl max-h-[85vh] rounded-[2rem] border border-google-border shadow-2xl flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6 md:p-8 border-b border-google-border flex items-center justify-between bg-google-bg/30">
          <h3 className="text-xl font-bold text-google-dark">{title}</h3>
          <button
            onClick={onClose}
            aria-label="Close"
            className="p-2 bg-google-bg rounded-full text-google-gray hover:text-google-dark hover:bg-google-border transition-all"
          >
            <X size={18} />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-6 md:p-8 text-sm text-google-dark leading-relaxed space-y-5 custom-scrollbar">
          <p className="text-[10px] uppercase tracking-widest text-google-gray font-bold">
            Last updated: {new Date().toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })}
          </p>
          {body.map((section, idx) => (
            <section key={idx} className="space-y-2">
              <h4 className="text-base font-bold text-google-dark">{section.heading}</h4>
              {section.paragraphs.map((p, j) => (
                <p key={j} className="text-google-gray">{p}</p>
              ))}
            </section>
          ))}
        </div>
        <div className="p-4 md:p-6 border-t border-google-border bg-google-bg/30 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-3 bg-google-blue text-google-bg rounded-xl text-xs font-bold uppercase tracking-widest shadow hover:brightness-110 transition-all"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

interface Section {
  heading: string;
  paragraphs: string[];
}

const TERMS_BODY: Section[] = [
  {
    heading: "1. Acceptance of Terms",
    paragraphs: [
      "By creating an account or using PRHOMZ AI Designer (the \"Service\"), you agree to be bound by these Terms & Conditions. If you do not agree, do not use the Service.",
    ],
  },
  {
    heading: "2. Use of the Service",
    paragraphs: [
      "The Service provides AI-assisted interior design visualization and product sourcing. You agree to use the Service only for lawful purposes and in compliance with all applicable laws.",
      "You are responsible for any content you upload, including ensuring that you have the rights to use such content.",
    ],
  },
  {
    heading: "3. Accounts and Quotas",
    paragraphs: [
      "Free and paid tiers carry usage quotas. We may modify quotas, features, or pricing with reasonable notice. Paid subscriptions renew automatically until cancelled from the customer portal.",
    ],
  },
  {
    heading: "4. Intellectual Property",
    paragraphs: [
      "Images generated by the Service from your inputs are yours to use for personal or commercial purposes, subject to applicable law. The underlying models, code, and brand remain the property of PRHOMZ Inc.",
    ],
  },
  {
    heading: "5. Disclaimers and Limitation of Liability",
    paragraphs: [
      "The Service is provided \"as is\" without warranties of any kind. Product recommendations are suggestions only; we are not responsible for third-party merchant pricing, availability, or quality.",
      "To the maximum extent permitted by law, PRHOMZ Inc shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.",
    ],
  },
  {
    heading: "6. Termination",
    paragraphs: [
      "We may suspend or terminate your account for breach of these terms. You may delete your account at any time from the account settings.",
    ],
  },
  {
    heading: "7. Changes to These Terms",
    paragraphs: [
      "We may update these terms from time to time. Continued use after changes constitutes acceptance of the revised terms.",
    ],
  },
  {
    heading: "8. Contact",
    paragraphs: [
      "Questions about these terms can be sent to support@prhomz.com.",
    ],
  },
];

const PRIVACY_BODY: Section[] = [
  {
    heading: "1. Information We Collect",
    paragraphs: [
      "We collect the account details you provide at signup — email address, username, gender, age range, postal/zip code, and country — along with images you upload for remodeling and usage metadata such as render counts, timestamps, and subscription tier.",
      "We also process your IP address to determine your approximate location (country level) so we can enable region-specific features such as Shop the Look. We do not use it to identify your precise location.",
    ],
  },
  {
    heading: "2. How We Use Information",
    paragraphs: [
      "Information is used to operate the Service, generate AI designs, enforce quotas, determine feature availability by region, process payments via our payment processor, and improve product quality.",
    ],
  },
  {
    heading: "3. Sharing",
    paragraphs: [
      "We share data only with service providers required to deliver the Service (cloud hosting, AI model providers, payment processor). We do not sell personal data.",
    ],
  },
  {
    heading: "4. Data Retention",
    paragraphs: [
      "Generated images and gallery content are retained for the period specified by your subscription tier; older items may be auto-expired. You may delete items at any time.",
    ],
  },
  {
    heading: "5. Security",
    paragraphs: [
      "We use industry-standard measures including encryption in transit and access controls. No system is perfectly secure; you use the Service at your own risk.",
    ],
  },
  {
    heading: "6. Your Rights",
    paragraphs: [
      "You may request access to, correction of, or deletion of your personal data. Contact us using the address below to make a request.",
    ],
  },
  {
    heading: "7. Children",
    paragraphs: [
      "The Service is not directed to children under 13. We do not knowingly collect personal data from children.",
    ],
  },
  {
    heading: "8. Changes",
    paragraphs: [
      "We may update this policy. Material changes will be communicated via the Service or email.",
    ],
  },
  {
    heading: "9. Contact",
    paragraphs: [
      "Privacy questions can be sent to support@prhomz.com.",
    ],
  },
];
